pipeline {
    agent none

    stages {
        stage('Checkout code') {
            agent any
            steps {
                echo "Checking out source code"
                // Jenkins already checked out the repo (Pipeline from SCM)
                sh 'ls -R'
            }
            }
        stage('Compile Java Program') {
            agent { 
                docker { image 'maven:3.9.6-eclipse-temurin-17' }
            }
            steps {
                sh '''
                    mkdir -p build
                    javac -d build src/HelloWorld.java
                '''
            }
        }
        stage('Run Java Program') {
            agent { 
                docker { image 'eclipse-temurin:17-jdk' }
            }
            steps {
                sh 'java -cp build HelloWorld'
            }
        }
    }    
}