pipeline {
    agent none

    stages {
        stage('Checkout code') {
            agent any
            steps {
                git branch: 'main', 
                url: 'https://github.com/srabhayraj/Jenkins_Playground/java-helloworld-multistage-multiagent.git'
                }
            }
        stage('Compile Java Program') {
            agent { 
                docker { image 'maven:3.9.6-eclipse-temurin-17' }
            }
            steps {
                sh '''
                    mkdir -p build
                    javac -d build src/HelloWorld.java
                '''
            }
        }
        stage('Run Java Program') {
            agent { 
                docker { image 'eclipse-temurin:17-jdk' }
            }
            steps {
                sh 'java -cp build HelloWorld'
            }
        }
    }    
}